# .github/workflows/debug-oidc.yml

name: OIDC Token Debug Dump

on:
  workflow_dispatch:
    inputs:
      role_to_test:
        description: 'The full ARN of the IAM role to test'
        required: true
      environment_name:
        description: 'The name of the environment to run in (e.g., development, or leave blank for none)'
        required: false

permissions:
  id-token: write
  contents: read

jobs:
  dump-the-token:
    name: Dump OIDC Token Payload
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}

    steps:
      - name: Attempt to Assume Role and Dump Token
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_to_test }}
          aws-region: eu-west-2
          # This is the crucial part that will dump the token payload
          log-level: debug
