# .github/workflows/deploy-platform.yml
name: Deploy Platform to AWS

on:
  push:
    branches: [ main ]
    paths: [ 'app/**', 'infrastructure/**', 'Dockerfile' ]
  pull_request:
    paths: [ 'infrastructure/**', 'Dockerfile' ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-application:
    name: Build and Push App to ECR
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    env:                               # <-- moved here (job-level)
      SELECTED_ENV: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    outputs:
      image_tag: ${{ steps.get-sha.outputs.sha }}
    steps:
      - name: Show selected environment
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "Selected environment=$SELECTED_ENV"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get short Git SHA
        id: get-sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ECR_IAM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: geyser-app
          IMAGE_TAG: ${{ steps.get-sha.outputs.sha }}
        run: |
          docker build --no-cache -f Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "Successfully pushed image with tag: $IMAGE_TAG"

  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: build-application
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    env:                               # shows which environment was selected
      SELECTED_ENV: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure
    steps:
      - name: Show selected environment   # shows which environment was selected
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "Selected environment=$SELECTED_ENV"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.TERRAFORM_IAM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Write terraform.tfvars from secret
        run: |
          umask 077
          cat > terraform.tfvars << 'EOF'
          ${{ secrets.TERRAFORM_TFVARS }}
          EOF

      - name: Terraform Init
        run: terraform init -input=false -lock-timeout=5m

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        env:
          IMAGE_TAG: ${{ needs.build-application.outputs.image_tag }}
        run: |
          terraform plan \
            -no-color \
            -input=false \
            -lock-timeout=5m \
            -var-file=terraform.tfvars \
            -var="image_version=${IMAGE_TAG}"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          IMAGE_TAG: ${{ needs.build-application.outputs.image_tag }}
        run: |
          terraform apply \
            -auto-approve \
            -input=false \
            -lock-timeout=5m \
            -var-file=terraform.tfvars \
            -var="image_version=${IMAGE_TAG}"
