# .github/workflows/deploy-infra.yml

name: Deploy Infrastructure to AWS

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'
  workflow_dispatch:

env:
  TF_WORKING_DIR: ./infrastructure
  AWS_REGION: eu-west-2

# MAKE THIS BLOCK IDENTICAL TO THE WORKING ECR WORKFLOW
permissions:
  id-token: write
  contents: read

jobs:
  # For this test, we will simplify to a single job again to be 100% sure
  terraform-plan-and-apply:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest
    # We remove the environment key again to ensure the simplest possible test case
    # NO environment key here

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Use the latest clean role
          role-to-assume: arn:aws:iam::488543428961:role/TerraformDeployerRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: ${{ env.TF_WORKING_DIR }}
