# .github/workflows/deploy-app-to-ecr.yml (TEMPORARILY MODIFIED FOR DEBUGGING)

name: Build and Push App to ECR # Name doesn't matter for the test

on:
  push:
    branches:
      - main

env:
  TF_WORKING_DIR: ./infrastructure
  AWS_REGION: eu-west-2

permissions:
  id-token: write # This is the known-good permissions block
  contents: read

jobs:
  # We will reuse this existing job structure
  build-and-push-image:
    name: 'DEBUGGING - Terraform Plan' # Renamed for clarity
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Point this known-good workflow at the Terraform Role
          role-to-assume: arn:aws:iam::488543428961:role/GitHubAction-Terraform-TerraFlow-Role
          aws-region: ${{ env.AWS_REGION }}

      # --- ADD THE TERRAFORM STEPS ---
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: ${{ env.TF_WORKING_DIR }}
